#!/usr/bin/perl

use strict;
use warnings;
use 5.010;

use lib 'lib';
use Data::Dumper;
use Hive;

my ($user, $pass) = @ARGV;

my $hive = Hive->new({
  username => $user,
  password => $pass,
});

foreach (qw[get_temperature get_target_temperature]) {
  say Dumper $hive->$_;
}