#!/usr/bin/perl

use strict;
use warnings;
use 5.010;

use lib 'lib';
use Data::Dumper;
use Hive;

die "Please give your Hive username and password\n" if @ARGV < 2;

my ($user, $pass) = @ARGV;

my $hive = Hive->new({
  username => $user,
  password => $pass,
});

say $hive->get_temperature;
say $hive->get_target_temperature;
say $hive->dump_temperature;
say $hive->dump_target_temperature;

foreach (qw[hubs devices]) {
  say Dumper $hive->$_;
}
